services:
  - type: web
    name: 539-ai-api
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app
    runtime: python
    build:
      pythonVersion: 3.10.12
