services:
  - type: web
    name: 539-ai-api
    env: python
    runtime: python
    buildCommand: pip install --upgrade pip setuptools wheel && pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn app:app
    build:
      pythonVersion: 3.10.13
